import csv

class TemplateGenerator:
    def __init__(self, csv_file, out_file):
        self.csv_file = csv_file
        self.out_file = out_file

    def generate(self):
        with open(self.csv_file, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            row = next(reader) 
        with open(self.out_file, "w", encoding="utf-8") as f:
            f.write("; SEL QuickSet Import Template\n")
            f.write("; Generated by Selprotopy\n\n")

            f.write("[Device]\n")
            f.write(f"Model={row['device']}\n")
            f.write(f"Serial={row['serial']}\n\n")

            f.write("[CT/PT]\n")
            f.write(f"CT Primary={row['ct_primary_A']}\n")
            f.write(f"CT Secondary={row['ct_secondary_A']}\n")
            f.write(f"PT Primary={row['pt_primary_V']}\n")
            f.write(f"PT Secondary={row['pt_secondary_V']}\n\n")

            f.write("[Protection]\n")
            f.write(f"50P1T Pickup={row['oc_50p1t_pickup_A']}\n")
            f.write(f"51P1T Time={row['oc_51p1t_time_s']}\n")
            f.write(f"51P1T Curve={row['oc_51p1t_curve']}\n")
            f.write(f"50Q1T Pickup={row['oc_50q1t_pickup_A']}\n")
            f.write(f"81D1T UnderFreq={row['uf_81d1t_freq_Hz']}\n")
            f.write(f"27P1T UnderVolt={row['uv_27p1t_pu']}\n\n")

            f.write("[Comm Port 1]\n")
            f.write(f"Baud={row['comm_port1_baud']}\n")
            f.write(f"Protocol={row['comm_port1_protocol']}\n")

        return self.out_file
